name: CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun run build --blogroll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out/www
      - uses: actions/deploy-pages@v4